### Project Meta
name: 'mitos'
config-version: 2
version: '0.1'

profile: 'mitos'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
   fail_fast: true

packages-install-path: "dbt_packages"
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"
packages:
  - package: dbt-labs/dbt_utils
    version: 1.2.0


require-dbt-version: [">=1.0.0", "<2.0.0"]
vars:
  car_speed: 21
  t_speed: 20
  rail_speed: 40
  intercity_speed: 125
  bus_speed: 12
  t_ratio: 0.5
  bus_ratio: 0.14
  rail_ratio: 0.35
  intercity_ratio: 0.01
  car_share_ratio: 0.4
  van_share_ratio: 0.2


models:
  mitos:
    +persist_docs:
      relation: true
      columns: true
    materialized: table
    staging:
      +meta:
        dagster:
          group: staging
      +schema: staging
      +tags:
        - staging
      materialized: view
    final:
      +meta:
        dagster:
          group: final
      +schema: final
      +materialized: view
      +tags:
        - final
seeds:
  mitos:
    +meta:
      dagster:
        group: landing
    +schema: raw
    +persist_docs:
      relation: true
      columns: true

snapshots:
  mitos:
    +target_schema: snapshots
    +meta:
      dagster:
        group: snapshots
