version: 2

models:
  - name: stg_travel_spending
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: expense_amount
      - name: expense_type
      - name: trip_end_date
      - name: cost_object
      - name: fiscal_year
      - name: cal_year
      - name: inflated_exp_amount
      - name: dlc_name
      - name: school_area
      - name: expense_group
        tests:
          - accepted_values:
              values: ['Air Travel', 'Ground Travel', 'Accommodations', 'Food', 'Other']
      - name: transport_mode
        tests:
          - accepted_values:
              values: ['misc.', 'housing', 'meals', 'car', 'train', 'ferry', 'air']
      - name: co2_factor
      - name: mtco2
