version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

  - name: stg_sus2017
    columns:
      - name: variable
      - name: exercise_rating
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
      - name: actionable
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
      - name: innovation
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
