version: 2

models:
  - name: stg_travel_spending
    description: "Business travel spending data enrinched by DLC, School Area, Expense Groups and Emission factors"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: expense_amount
        description: expense amount in dollar
      - name: expense_type
        description: expense type
      - name: trip_end_date
        description: date of expense
      - name: cost_object
        description: DLC cost object ID
      - name: fiscal_year
        description: MIT fiscal year July to June
      - name: cal_year
        description: Expense record year
      - name: inflated_exp_amount
        description: Adjusted to 2023 dollar using annual CPI index
      - name: dlc_name
        description: Department, Lab and Center name
      - name: school_area
        description: School Area
      - name: expense_group
        description: Larger Expense Group
        tests:
          - accepted_values:
              values: ['Air Travel', 'Ground Travel', 'Accommodations', 'Food', 'Other']
      - name: transport_mode
        description: Transport Mode for GHG calculation
        tests:
          - accepted_values:
              values: ['misc.', 'housing', 'meals', 'car', 'train', 'ferry', 'air']
      - name: co2_factor
        description: CO2 emission factor in kg/$ from USEEIO_v2 using 2012 dollars
      - name: mtco2
        description: CO2 emission in megatons
  - name: stg_cost_object_rollup
    description: "Mapping database for cost_object ID to DLC and School areas, grouped into larger school areas"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: cost_object
        description: "Cost Object ID"
        tests:
          - unique
      - name: dlc_name
        description: "MIT Department, Lab, and Center name"
      - name: school_area
        description: "School Area"
  - name: stg_construction_expense
    description: "Adjusted fiscal year construction cost and GHG emission"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: fiscal_year
        description: "Fiscal Year"
      - name: expense_type
        description: "Type of expense, relevant for emission factor selection"
      - name: expense_in_million_2021_equivalent
        description: "expense in million dollars adjusted to 2021 dollars"
      - name: ghg_emission
        description: "eCO2 GHG emission in megatons"
  - name: stg_dof_mainenance_cost
    description: "Adjusted fiscal year maintenance cost and GHG emission"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: fiscal_year
        description: "Fiscal Year"
      - name: expense_type
        description: "Type of expense, relevant for emission factor selection and understanding"
      - name: expense_2021_equivalent
        description: "maintenance cost from DOF adjusted to 2021 dollars"
      - name: ghg_emission
        description: "eCO2 GHG emission in megatons"
  - name: stg_waste_recycle
    description: "Processed (renamed and mapped) Waste recycle data from 2010 to 2023 June"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "service_date"
        description: "Service Date"
      - name: "customer_name"
        description: "Name of te service site"
      - name: "material"
        description: "Waste category"
      - name: "diverted"
        description: "Tons being diverted"
      - name: "tons"
        description: "Total tonnage of waste collected"
  - name: stg_commuting_survey_2018
    description: "Estimated GHG emissions from Commuting Survey 2018."
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: "miles"
        description: "Daily commute miles by mode"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
