version: 2

models:
  - name: stg_travel_spending
    description: "Business travel spending data enrinched by DLC, School Area, Expense Groups and Emission factors"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: expense_amount
        description: expense amount in dollar
      - name: expense_type
        description: expense type
      - name: trip_end_date
        description: date of expense
      - name: cost_object
        description: DLC cost object ID
      - name: fiscal_year
        description: MIT fiscal year July to June
      - name: cal_year
        description: Expense record year
      - name: inflated_exp_amount
        description: Adjusted to 2023 dollar using annual CPI index
      - name: dlc_name
        description: Department, Lab and Center name
      - name: school_area
        description: School Area
      - name: expense_group
        description: Larger Expense Group
        data_tests:
          - accepted_values:
              values: ['Air Travel', 'Ground Travel', 'Accommodations', 'Food', 'Other']
      - name: transport_mode
        description: Transport Mode for GHG calculation
        data_tests:
          - accepted_values:
              values: ['misc.', 'housing', 'meals', 'car', 'train', 'ferry', 'air']
      - name: co2_factor
        description: CO2 emission factor in kg/$ from USEEIO_v2 using 2012 dollars
      - name: mtco2
        description: CO2 emission in megatons
  - name: stg_cost_object_rollup
    description: "Mapping database for cost_object ID to DLC and School areas, grouped into larger school areas"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: cost_object
        description: "Cost Object ID"
      - name: dlc_name
        description: "MIT Department, Lab, and Center name"
      - name: school_area
        description: "School Area"
  - name: stg_construction_expense
    description: "Adjusted fiscal year construction cost and GHG emission"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: fiscal_year
        description: "Fiscal Year"
      - name: expense_type
        description: "Type of expense, relevant for emission factor selection"
      - name: expense_in_million_2021_equivalent
        description: "expense in million dollars adjusted to 2021 dollars"
      - name: ghg_emission
        description: "eCO2 GHG emission in megatons"
  - name: stg_dof_maintenance_cost
    description: "Adjusted fiscal year maintenance cost and GHG emission"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: fiscal_year
        description: "Fiscal Year"
      - name: expense_type
        description: "Type of expense, relevant for emission factor selection and understanding"
      - name: expense_2021_equivalent
        description: "maintenance cost from DOF adjusted to 2021 dollars"
      - name: ghg_emission
        description: "eCO2 GHG emission in megatons"
  - name: stg_waste_recycle
    description: "Processed (renamed and mapped) Waste recycle data from 2010 to 2023 June"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "service_date"
        description: "Service Date"
      - name: "customer_name"
        description: "Name of te service site"
      - name: "material"
        description: "Waste category"
      - name: "diverted"
        description: "Tons being diverted"
      - name: "tons"
        description: "Total tonnage of waste collected"
  - name: stg_commuting_survey_2018
    description: "Estimated GHG emissions from Commuting Survey 2018."
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: "share"
        description: "Share of people using the mode in the year"
      - name: "miles"
        description: "Daily commute miles by mode"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
  - name: stg_commuting_survey_2021
    description: "Estimated GHG emissions from Commuting Survey 2021."
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: "share"
        description: "Share of people using the mode in the year"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
  - name: stg_commuting_survey_2023
    description: "Estimated GHG emissions from Commuting Survey 2023."
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: "share"
        description: "Share of people using the mode in the year"
      - name: "miles"
        description: "Weekly commute miles by mode"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
  - name: stg_parking_daily
    description: "Merged parking data from selected lots"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "date"
        description: "Service Date"
      - name: "unique_1016"
        description: "Daily unique parker for lot 1016"
      - name: "unique_1018"
        description: "Daily unique parker for lot 1018"
      - name: "unique_1022"
        description: "Daily unique parker for lot 1022"
      - name: "unique_1024"
        description: "Daily unique parker for lot 1024"
      - name: "unique_1025"
        description: "Daily unique parker for lot 1025"
      - name: "unique_1030"
        description: "Daily unique parker for lot 1030"
      - name: "unique_1035"
        description: "Daily unique parker for lot 1035"
      - name: "unique_1037"
        description: "Daily unique parker for lot 1037"
      - name: "unique_1038"
        description: "Daily unique parker for lot 1038"
      - name: "total_unique"
        description: "Daily unique parker for all lots"
  - name: stg_purchased_goods_invoice
    description: "CPI adjusted and GHG emission enriched invoice data for purchased goods"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "sap_invoice_number"
        description: "Unique identifier for SAP-generated invoices."
      - name: "invoice_number"
        description: "General identifier for invoices, distinct from SAP-specific IDs."
      - name: "fiscal_year"
        description: "The fiscal year in which the transaction was recorded or relevant."
      - name: "po_number"
        description: "Purchase Order number associated with the invoice"
      - name: "level_1"
        description: "General goods and service category"
      - name: "level_2"
        description: "Rolled up commodity category"
      - name: "level_3"
        description: "Lowest level detailed commodity categorization."
      - name: "total"
        description: "Total USD spend for the invoice"
      - name: "description"
        description: "Descriptive details about the invoice"
      - name: "billing"
        description: "Billing information."
      - name: "supplier"
        description: "Name or identifier of the supplier or service provider."
      - name: "supplier_number"
        description: "Unique number or identifier assigned to the supplier."
      - name: "cost_object"
        description: "MIT cost object associated with the invoice."
      - name: "code"
        description: "USEEIO code to map to emission factor"
      - name: "emission_factor"
        description: "GHG emission factor from USEEIO/NAICS table."
      - name: "adjusted_spend_2021"
        description: "Adjusted spend total to 2021 USD for GHG calculation."
      - name: "inflated_spend"
        description: "CPI adjusted spend total to current year."
      - name: "dlc_name"
        description: "Department, Lab, and Center name."
      - name: "ghg"
        description: "Greenhouse gas data related in kg CO2e"
  - name: stg_food_order
    description: "Food order data with SIMAP category and GHG emission"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: customer_name
        description: "Dinning hall name"
      - name: contract_month
        description: "Contract month of the order"
      - name: fiscal_year
        description: "Fiscal year of the order"
      - name: mfr_item_description
        description: "Manufacturer item description"
      - name: dist_item_description
        description: "Distributor description"
      - name: lbs
        description: "Weight in lbs"
      - name: gal
        description: "Volume in gallon"
      - name: spend
        description: "Dollar spend"
      - name: wri_category
        description: "World Resource Institute food category"
      - name: simap_category
        description: "SIMAP food category"
      - name: spend_emission_factor
        description: "GHG emission factor in kg/2021 USD"
      - name: weight_emission_factor
        description: "GHG emission factor in kg CO2e/kg Food"
      - name: weight_kg
        description: "Weight in kg"
      - name: co2eq
        description: "GHG emission in kg CO2e"
  - name: stg_waste_emission
    description: "Scope 3 waste emission with emission factors"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: service_month
        description: "Service Month"
      - name: material
        description: "Waste material stream"
      - name: tons
        description: "waste tonnage"
      - name: tons_adjusted
        description: "waste tonnage adjusted by specified splits"
      - name: emission_factor
        description: "GHG emission factor in kg CO2e/ton"
      - name: co2eq
        description: "Total GHG emission in kg CO2 equivalence"
      - name: year
        description: "Service year"

unit_tests:
  - name: test_waste_split_adjustment
    description: >
      Scenario: Waste Streams per knowledge:
        - 22% of recycle to trash
        - 90% of hard-to-recycle to recycle
        - 50% of C & D to recycle
    model: stg_waste_emission
    given:
      - input: source("raw", "waste_emission_factors_EPA")
        rows: []
      - input: ref("final_waste_recycle")
        rows:
          - { service_date: '2020-04-01', customer_name: 'dummy', material: 'C & D', diverted: 0, tons: 20 }
          - { service_date: '2020-04-01', customer_name: 'dummy', material: 'Trash', diverted: 0, tons: 50 }
          - { service_date: '2020-04-01', customer_name: 'dummy', material: 'Hard-to-Recycle Materials', diverted: 0, tons: 10 }
          - { service_date: '2020-04-01', customer_name: 'dummy', material: 'Recycling', diverted: 0, tons: 10 }
    expect:
      rows:
          - { service_month: '2020-04-01', material: 'C & D', tons_adjusted: 10, tons: 20, co2eq: NULL, year: 2020}
          - { service_month: '2020-04-01', material: 'Trash', tons_adjusted: 52.2, tons: 50, co2eq: NULL, year: 2020 }
          - { service_month: '2020-04-01', material: 'Hard-to-Recycle Materials', tons_adjusted: 1, tons: 10, co2eq: NULL, year: 2020 }
          - { service_month: '2020-04-01', material: 'Recycling', tons_adjusted: 26.8, tons: 10, co2eq: NULL, year: 2020 }
