version: 2

models:
  - name: travel_FY_school_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY, School Area and Expense Groups
    columns:
      - name: school_area
        description: School Area
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: group_mtco2
        description: Total CO2 emission of each expense group/school area
      - name: group_expense_amount
        description: Expense total of each expense group/school area
      - name: share_of_total_mtco2
        description: CO2 emission share of each expense group/school area
      - name: share_of_total_expense_amount
        description: Expense share of each expense group/school area

  - name: travel_FY_dlc_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY, DLC and Expense Groups
    columns:
      - name: dlc_name
        description: Department, Lab or Center
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: group_mtco2
        description: Total CO2 emission of each expense group/DLCs
      - name: group_expense_amount
        description: Expense total of each expense group/DLCs
      - name: share_of_total_mtco2
        description: CO2 emission share of each expense group/DLCs
      - name: share_of_total_expense_amount
        description: Expense share of each expense group/DLCs

  - name: travel_FY_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY and Expense Groups
    columns:
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: expense_total
        description: Expense total of each expense group
      - name: expense_amount_share
        description: Expense share of each expense group
      - name: mtCO2_total
        description: Total CO2 emission of each expense group
      - name: mtCO2_share
        description: Total CO2 emission of each expense group

  - name: construction_expense_emission
    meta:
      owner: yu_cheng@mit.edu
    description: Construction expense and GHG emission broken down by expense type
    columns:
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_type
        description: Type of construction expense
        tests:
          - accepted_values:
              values: ['New Construction', 'Maintenance material and Services', 'Renovation and Renewal']
      - name: expense_2021
        description: Expense in million dollars adjusted to 2021 dollars
      - name: ghg_emission
        description: Total CO2 emission of each expense type

  - name: final_waste_recycle
    description: "Up-to-date waste collection and recycling data from Facilities including small streams"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "service_date"
        description: "Service Date"
      - name: "customer_name"
        description: "Name of te service site"
      - name: "material"
        description: "Waste category"
      - name: "diverted"
        description: "Tons being diverted"
      - name: "tons"
        description: "Total tonnage of waste collected"
  - name: commuting_emission
    description: "Estimated GHG Scope3 commuting emissions"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
      - name: year
        description: "Survey year"
        tests:
          - accepted_values:
              values: [2018, 2021, 2023]
