version: 2

models:
  - name: travel_FY_school_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY, School Area and Expense Groups
    columns:
      - name: school_area
        description: School Area
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: group_mtco2
        description: Total CO2 emission of each expense group/school area
      - name: group_expense_amount
        description: Expense total of each expense group/school area
      - name: share_of_total_mtco2
        description: CO2 emission share of each expense group/school area
      - name: share_of_total_expense_amount
        description: Expense share of each expense group/school area

  - name: travel_FY_dlc_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY, DLC and Expense Groups
    columns:
      - name: dlc_name
        description: Department, Lab or Center
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: group_mtco2
        description: Total CO2 emission of each expense group/DLCs
      - name: group_expense_amount
        description: Expense total of each expense group/DLCs
      - name: share_of_total_mtco2
        description: CO2 emission share of each expense group/DLCs
      - name: share_of_total_expense_amount
        description: Expense share of each expense group/DLCs

  - name: travel_FY_exp_group_summary
    meta:
      owner: yu_cheng@mit.edu
    description: Business travel spending amount and CO2 emission grouped by FY and Expense Groups
    columns:
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_group
        description: Larger Expense Group
      - name: expense_total
        description: Expense total of each expense group
      - name: expense_amount_share
        description: Expense share of each expense group
      - name: mtCO2_total
        description: Total CO2 emission of each expense group
      - name: mtCO2_share
        description: Total CO2 emission of each expense group

  - name: construction_expense_emission
    meta:
      owner: yu_cheng@mit.edu
    description: Construction expense and GHG emission broken down by expense type
    columns:
      - name: fiscal_year
        description: MIT Fiscal year July-June
      - name: expense_type
        description: Type of construction expense
        data_tests:
          - accepted_values:
              values: ['New Construction', 'Maintenance material and Services', 'Renovation and Renewal']
      - name: expense_2021
        description: Expense in million dollars adjusted to 2021 dollars
      - name: ghg_emission
        description: Total CO2 emission of each expense type

  - name: final_waste_recycle
    description: "Up-to-date waste collection and recycling data from Facilities including small streams"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "service_date"
        description: "Service Date"
      - name: "customer_name"
        description: "Name of te service site"
      - name: "material"
        description: "Waste category"
      - name: "diverted"
        description: "Tons being diverted"
      - name: "tons"
        description: "Total tonnage of waste collected"
  - name: commuting_emission
    description: "Estimated GHG Scope3 commuting emissions"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "mode"
        description: "Commute mode"
      - name: "share"
        description: "Share of people using the mode in the year"
      - name: mtco2
        description: "Anual equivalent CO2 emission in metric tons"
      - name: year
        description: "Survey year"
        data_tests:
          - accepted_values:
              values: [2018, 2021, 2023]
  - name: purchased_goods_invoice_summary
    description: "Summary of purchased goods invoices grouped by level 3 category"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: "level_3"
        description: "Lowest level detailed commodity categorization."
      - name: fiscal_year
        description: "MIT Fiscal year from July to June"
      - name: mtco2
        description: "Metric tons CO2e emission"
      - name: spend_usd
        description: "Spend in USD inflated to current year"
      - name: "level_1"
        description: "General goods and service category"
      - name: "level_2"
        description: "Rolled up commodity category"
      - name: share_mtco2
        description: "Percentage share of total CO2 emission"
      - name: share_spend
        description: "Percentage share of dollar spend"
  - name: purchased_goods_invoice_po_summary
    description: "Summary of purchased goods invoices grouped by PO_number"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: po_number
        description: "Purchased Order number"
      - name: fiscal_year
        description: "MIT Fiscal year from July to June"
      - name: "level_3"
        description: "Lowest level detailed commodity categorization."
      - name: mtco2
        description: "Metric tons CO2e emission"
      - name: spend_usd
        description: "Spend in USD inflated to current year"
      - name: "level_1"
        description: "General goods and service category"
      - name: "level_2"
        description: "Rolled up commodity category"
      - name: "description"
        description: "Descriptive details about the invoice"
  - name: purchased_goods_invoice_supplier_summary
    description: "Summary of purchased goods invoices grouped by supplier number"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: fiscal_year
        description: "MIT Fiscal year from July to June"
      - name: supplier_number
        description: "supplier number"
      - name: mtco2
        description: "Metric tons CO2e emission"
      - name: spend_usd
        description: "Spend in USD inflated to current year"
      - name: "level_3"
        description: "Lowest level detailed commodity categorization."
      - name: supplier
        description: "supplier name"
      - name: "description"
        description: "Descriptive details about the invoice"
  - name: final_waste_emission
    description: "Summary of Scope 3 waste emission grouped by material"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: year
        description: "Calendar Year of Service Date"
      - name: material
        description: "Waste stream"
      - name: tons
        description: "Waste tonnage"
      - name: co2eq
        description: "Metric tons CO2e emission"
  - name: final_ghg_inventory
    description: "Aggregate all scopes GHG emissions of the specified fiscal_year"
    meta:
      owner: yu_cheng@mit.edu
    columns:
      - name: category
        description: "GHG category"
      - name: emission
        description: "GHG emission in metric tons"
      - name: fiscal_year
        description: "MIT fiscal year"
      - name: scope
        description: "GHG scope 1, 2, or 3"
      - name: last_update
        description: "Timestamp of the entry being added"
