version: 2

sources:
  - name: raw
    description: Raw data in the MITOS warehouse, including reference tables and asset ingested data
    schema: raw
    meta:
      owner: yu_cheng@mit.edu
    loader: Dagster
    tables:
      - name: travel_spending
        description: "Travel Spending data from VPF"
        meta:
          dagster:
            asset_key: ["travel_spending"]
        columns:
          - name: expense_amount
            description: "Reimbursed amount in dollar"
          - name: expense_type
            description: "Type of the expense"
          - name: trip_end_date
            description: "Trip end date"
          - name: cost_object
            description: "DLC cost object ID"
          - name: last_update
            description: "Timestamp of the entry being added"
      - name: annual_cpi_index
        description: "Consumer Price Index data from python CPI library. "
        meta:
          dagster:
            asset_key: ["annual_cpi_index"]
        columns:
          - name: year
          - name: value
          - name: series_id
            description: "Consumer Price Index ID"
          - name: series_title
            description: "Consumer Price Index name"
      - name: cost_object_warehouse
        description: "Mapping database for cost_object ID to DLC and School area from MIT data warehouse"
        meta:
          dagster:
            asset_key: ["cost_object_warehouse"]
        columns:
          - name: cost_object
            description: "Cost Object ID"
            tests:
              - unique
          - name: dlc_name
            description: "MIT Department, Lab, and Center name"
          - name: school_area
            description: "School Area"
          - name: cost_collector_effective_date
            description: "Cost Collector ID effective since"
          - name: last_update
            description: "Date of last update"
      - name: expense_emission_mapper
        description: "Mapping database for expense type to transport mode required for CO2 factor matching"
        meta:
          dagster:
            asset_key: ["expense_emission_mapper"]
        columns:
          - name: expense_type
          - name: emission_category
            description: "Larger GHG emission group"
            tests:
              - not_null
      - name: construction_expense
        description: "Construction expense data from VPCSS"
        meta:
          dagster:
            asset_key: ["construction_expense"]
        columns:
          - name: new_construction
            description: "New construction expense in Million"
          - name: renovation_and_renewal
            description: "Renovation and Renewal expense in Million"
          - name: fiscal_year
            tests:
              - unique
      - name: dof_maintenance_cost
        description: "Maintenance and service cost data from Facilities"
        meta:
          dagster:
            asset_key: ["dof_maintenance_cost"]
        columns:
          - name: fiscal_year
            tests:
              - unique
          - name: Work Orders Within DOF
            description: "Work Orders within Department of Facilities"
          - name: Sales Work Orders
            description: "Sales work orders from Department of Facilities"
          - name: DOF Ops Costs Outside of Wos
            description: "Operation costs outside of work orders"
      - name: emission_factor_naics
        description: "NAICS Supply chain Emission factor (v1.2) merged with USEEIO code"
        meta:
          dagster:
            asset_key: ["emission_factor_naics"]
        columns:
          - name: ID
            description: "USEEIO code with region"
            tests:
              - unique
          - name: emission_factor
            description: "eCO2 emission factor in kg/$ from USEEIOv2.0 (2012 dollars)"
          - name: Name
            description: "USEEIO description"
          - name: Code
            description: "USEEIO Code"
          - name: Category
            description: "USEEIO Category"
          - name: Description
            description: "BEA code and name"
          - name: Supply Chain Emission Factors without Margins
          - name: Margins of Supply Chain Emission Factors
          - name: Supply Chain Emission Factors with Margins
            description: "eCO2 emission factor in kg/$ of NAICSv1.2 (2021 dollars)"
      - name: emission_factor_useeio_v2
        description: "USEEIO_v2 The US Environmentally-Extended Input-Output Model"
        meta:
          dagster:
            asset_key: ["emission_factor_useeio_v2"]
        columns:
          - name: ID
            description: "USEEIO code with region"
            tests:
              - unique
          - name: emission_factor
            description: "eCO2 emission factor in kg/$ from USEEIOv2.0 (2012 dollars)"
          - name: Name
            description: "USEEIO description"
          - name: Code
            description: "USEEIO Code"
          - name: Category
            description: "USEEIO Category"
          - name: Description
            description: "BEA code and name"
      - name: historical_waste_recycle
        description: "Waste recycle data from 2010 to 2023 June"
        meta:
          dagster:
            asset_key: ["historical_waste_recycle"]
        columns:
          - name: "Date (YYYY-MM-DD)"
            description: "Service Date"
          - name: "Building Name"
            description: "Name of te service site"
          - name: "Waste Stream"
            description: "Waste category"
          - name: "Disposed Tonnage"
            description: "Tons being disposed"
          - name: "Diverted Tonnage"
            description: "Tons being diverted"
          - name: "Total Tonnage"
            description: "Total tonnage of waste collected"
      - name: newbatch_waste_recycle
        description: "Waste recycle data from 2023 July to December"
        meta:
          dagster:
            asset_key: ["newbatch_waste_recycle"]
        columns:
          - name: "Customer Key"
            description: "Waste collection building id"
          - name: "Customer Name"
            description: "Waste collection building name"
          - name: "Service Street"
            description: "Waste collection site street"
          - name: "Service Date"
            description: "Service Date"
          - name: "Material"
            description: "Waste category"
          - name: "Tons"
            description: "Total tonnage of waste collected"
      - name: small_stream_recycle
        description: "Small Stream recycle data collected an maintained by Facilities, currently only ingest 2023"
        meta:
          dagster:
            asset_key: ["small_stream_recycle"]
        columns:
          - name: "service_date"
            description: "Service Date"
          - name: "customer_name"
            description: "Name of te service site"
          - name: "material"
            description: "Waste category"
          - name: "diverted"
            description: "Tons being diverted"
          - name: "tons"
            description: "Total tonnage of waste collected"
      - name: commuting_survey_2018
        description: "Commuting Survey 2018 from IR, commuting time broken down by commuting modes"
        meta:
          dagster:
            asset_key: ["commuting_survey_2018"]
        columns:
          - name: "commute_time"
            description: "Commute time bins"
          - name: "drive_alone"
            description: "Count of people driving alone"
          - name: "drive_alone_and_public_transport"
            description: "Count of people driving alone and using public transport"
          - name: "walk_and_public_transport"
            description: "Count of people walking and using public transport"
          - name: "drop_off_and_public_transport"
            description: "Count of people being dropped off and using public transport"
          - name: "bike_and_public_transport"
            description: "Count of people biking and using public transport"
          - name: "carpooled(2-6)"
            description: "Count of people carpooling with 2-6 people"
          - name: "vanpooled(7+)"
            description: "Count of people vanpooling with 7+ people"
          - name: "dropped_off"
            description: "Count of people being dropped off"
          - name: "taxi_and_ride_service"
            description: "Count of people using taxi and ride service"
          - name: "bicycled"
            description: "Count of people biking"
          - name: "walked"
            description: "Count of people walking"
          - name: "Remote"
            description: "Count of people working remotely"
          - name: "other"
            description: "Count of people using other commuting modes"
          - name: "unknown"
            description: "Count of people with unknown commuting modes"
          - name: "no_answer"
            description: "Count of people not answering"
          - name: "commute_time_average_hours"
            description: "Average commute time in hours"
      - name: commuting_emission_factors_EPA
        description: "Emission factors for commuting modes from EPA 2024 data"
        meta:
          dagster:
            asset_key: ["commuting_emission_factors_EPA"]
        columns:
          - name: "vehicle_type"
            description: "Vehicle type"
          - name: "CO2_kg"
            description: "Emission factors of CO2 in kg/mile"
          - name: "CH4_g"
            description: "Emission factors of CH4 in g/mile"
          - name: "N2O_g"
            description: "Emission factors of N2O in g/mile"
          - name: "units"
            description: "Emission factors units"
          - name: "CO2eq_kg"
            description: "Emission factors of equivalent CO2 combining three GHGs using GWP in kg/mile"
          - name: last_update
            description: "Timestamp of the entry being added"
      - name: commuting_survey_2021
        description: "Commuting Survey 2021 from IR, total commuting time of different roles broken down by commuting modes"
        meta:
          dagster:
            asset_key: ["commuting_survey_2021"]
        columns:
          - name: "drove_alone"
            description: "Minutes of driving alone"
          - name: "carpooled(2-6)"
            description: "Minutes of carpooling with 2-6 people"
          - name: "vanpooled(7+)"
            description: "Minutes of vanpooling with 7+ people"
          - name: "shuttle"
            description: "Minutes of using shuttle"
          - name: "public transportation"
            description: "Minutes of using public transportation"
      - name: commuting_survey_2023
        description: "Commuting Survey 2023 from IR, commuting time broken down by commuting modes"
        meta:
          dagster:
            asset_key: ["commuting_survey_2023"]
        columns:
          - name: "commute_time_average"
            description: "Average commute time in hours"
          - name: "drove_alone"
            description: "Count of people driving alone"
          - name: "carpooled(2-6)"
            description: "Count of people carpooling with 2-6 people"
          - name: "vanpooled(7+)"
            description: "Count of people vanpooling with 7+ people"
          - name: "shuttle"
            description: "Count of people using shuttle"
          - name: "public transportation"
            description: "Count of people using public transportation"
      - name: commuting_survey_modes
        description: "Commuting modes breakdown from commuting survey 2018, 2021 and 2023"
        meta:
          dagster:
            asset_key: ["commuting_survey_modes"]
        columns:
          - name: "mode"
            description: "Commute mode"
          - name: "count"
            description: "Daily average of people using the mode"
          - name: "year"
            description: "Year of the survey"
      - name: historical_parking_daily
        description: "Parking data till June 25 2021"
        meta:
          dagster:
            asset_key: ["historical_parking_daily"]
        columns:
          - name: "date"
            description: "Service Date"
          - name: "unique_1016"
            description: "Daily unique parker for lot 1016"
          - name: "unique_1018"
            description: "Daily unique parker for lot 1018"
          - name: "unique_1022"
            description: "Daily unique parker for lot 1022"
          - name: "unique_1024"
            description: "Daily unique parker for lot 1024"
          - name: "unique_1025"
            description: "Daily unique parker for lot 1025"
          - name: "unique_1030"
            description: "Daily unique parker for lot 1030"
          - name: "unique_1035"
            description: "Daily unique parker for lot 1035"
          - name: "unique_1037"
            description: "Daily unique parker for lot 1037"
          - name: "unique_1038"
            description: "Daily unique parker for lot 1038"
          - name: "total_unique"
            description: "Daily unique parker for all lots"
      - name: newbatch_parking_daily
        description: "New daily parking activity since 2023 June 25"
        meta:
          dagster:
            asset_key: ["newbatch_parking_daily"]
        columns:
          - name: "date"
            description: "Date of the parking activity"
          - name: "parking_lot"
            description: "Parking lot ID"
          - name: "total"
            description: "Total parking count"
          - name: "unique"
            description: "Unique parking count"
          - name: "last_update"
            description: "update timestamp"
      - name: mit_holidays
        description: "MIT holidays since 2015, required for Prophet model"
        meta:
          dagster:
            asset_key: ["mit_holidays"]
        columns:
          - name: "date"
            description: "date of the holiday"
          - name: "holiday"
            description: "holiday description"
          - name: "holiday_type"
            description: "Type of holiday"
          - name: "last_update"
            description: "update timestamp"
